# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c39dce87d6ec593e938626be529ad64cf6d821a437ecfea5c0fc367d1c3c29ca033b4036b59728073abc1e5e1b519c864b6adffd81b7af82dd480181762941e

test:
  secret_key_base: c04d051ff5cc53aa732534d3d852256db4fe8ca471c45685549d48f8c999d2038b6804db005c98af7c0e424295afed5860260e264225aa4b2126441ea16be8fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
